branch: main
committer_email: george@re
committer_name: george
markdown_dir: markdown/
repo_path: /home/gvauter/repos/gvauter/trestlebot-cli-test
upstreams:
  sources:
    - "https://github.com/RedHatProductSecurity/oscal-profiles@main"
  skip_validation: false
  include_models:
    - "*"
